# Generated by Django 4.0.4 on 2022-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favorite_age_favorite_breed_favorite_cats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='shelter',
            field=models.CharField(default='12abc', max_length=255),
            preserve_default=False,
        ),
    ]
